version: '3'
services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: /data/tasks.db
      PORT: 8080
    volumes:
      - tasks_data:/data
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:80"
volumes:
  tasks_data:
