# fly.toml app configuration file generated for bigpicture-backend on 2024-11-12T23:33:56-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bigpicture-backend'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  CORS_ORIGINS = 'https://bigpicture-frontend-ancient-night-2172.fly.dev,http://localhost:5173'
  FLASK_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'bigpicture_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
